version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    # depends_on:
    #   - postgres
    # command: ["/app/wait-for-it.sh", "postgres:5432", "-t", "30", "--", "python3", "-m", "uvicorn", "fin_pool.main:app", "--host", "0.0.0.0", "--port", "8000"]
  postgres:
    image: postgres:latest
    container_name: finance_tracker_db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finPool
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/